### ISSUE TITLE
일정 목록 조회 API 구현

### ISSUE THREAD

**Issue by princenim** [f-lab-edu/kbo-ticketing#15]
## Description
- 야구 일정 목록 조회 API 구현

## Task 
- [x] 월, 일, 일 구장 별 필터링 기능
- [x] controller, service 유닛 테스트 
- [ ] 후에 페이지네이션 추가하기 ⭐⭐⭐⭐⭐⭐
