### ISSUE TITLE
회원가입 API 구현

### ISSUE THREAD

**Issue by princenim** [f-lab-edu/kbo-ticketing#2]
## Description
- 회원가입 기능 구현 

## Task
- [x] 패키지 구조 고민하기
- [x] db 설정 및 mybatis config 설정하기
- [x] 회원가입 기능 구현하기
- [x] 회원가입 유효성(validation) 체크하기 
- [x] 비밀번호 암호화해서 DB에 저장하기
- [x] 테스트 코드 공부하기 및 작성하기 
- [x] 이메일 인증번호 확인 로직 추가
