### ISSUE TITLE
nGrinder와 Pinpoint를 이용한 성능 테스트 

### ISSUE THREAD

**Issue by princenim** [f-lab-edu/kbo-ticketing#21]
## Description
nGrinder와 Pinpoint를 이용한 성능 테스트

## Task 
- [x] ngrinder 설치
- [x] 테스트 시나리오 작성 및 테스트 
- [x] 모니터링 서버 구축 
- [x] Pinpoint 세팅
- [x] 문제점 및 병목지점 파악
- [x] 개선하기
   - [x] Redis 캐싱  
   - [x] nginx
   - [x] Scale out
   - [x] Connection pool 조절
