### ISSUE TITLE
좌석 선택 및 예매 API

### ISSUE THREAD

**Issue by princenim** [f-lab-edu/kbo-ticketing#26]
## Description
<img width="410" alt="319183329-ea879e18-499a-47d4-90ca-c9ea41b398eb" src="https://github.com/f-lab-edu/kbo-ticketing/assets/59499600/cc354755-0022-4ebd-a2da-9fd1e9b2e2dd">

- **좌석 선택 API**
1. 좌석을 선택하면 7분 동안 타인이 좌석 선택 불가능하다. 
2. 유효기간이 지나면 좌석을 다시 선택해야한다. 

- **예매하기 API** 
1.  좌석 선점 != 예매 (좌석을 7분동안 선점할수있고 후에 예매가능)
2.  경기 당  `예매가능한 횟수`와 `예매가능한 최대 좌석 개수`가 다르다. 
   - 잠실구장의 3월 12일 경기는 총 2번 예매 가능하다. 1루좌석은 예매당 6장까지 예매가능하고, 외야좌석은 예매당 3장까지 예매가능하다.
   - 문학구장의 3월 13일 경기는 총 1번 예매 가능하다. 1루 좌석은 예매당 3장까지 예매가능하고, 외야좌석도 3장까지 예매가능하다.

## Task
- [x] 좌석 선택 API
- [x] 예매하기 API 
- [x] unit test 추가
- [x] redis 를 이용해 7분동안 자리 선점할수있도록 기능 만들기
