### ISSUE TITLE
인증번호 전송 API 구현

### ISSUE THREAD

**Issue by princenim** [f-lab-edu/kbo-ticketing#8]
## Description
인증번호 전송 API 구현

## Task
- [x] Redis 설정 및 세팅
- [x] Redis TTL 설정해 인증번호 저장 기능 구현
- [x] SMTP로 메일 전송 기능 구현
- [x] 유닛 테스트 코드 작성
- [ ] Redis 공부
